export const iiit = [
  {
    name: "Harsh Prakash",
    org: "IIIT Pune",
    img: "harsh.jpg",
    linkedin: "https://www.linkedin.com/in/harsh132/",
    github: "https://github.com/harsh132",
    codechef: "https://www.codechef.com/users/harsh132",
    year: "nineteen",
  },
  {
    name: "Darshan Lokhande",
    org: "IIIT Pune",
    img: "3.jpeg",
    linkedin: "https://www.linkedin.com/in/darshanlokhande/",
    github: "https://github.com/darshancool25",
    codechef: "https://www.codechef.com/users/darshancool25",
    year: "eighteen",
  },
  {
    name: "Himanshu Sharma",
    org: "IIIT Pune",
    img: "himanshu.jpeg",
    linkedin: "https://www.linkedin.com/in/himanshu-sharma-034713145/",
    github: "",
    codechef: "https://www.codechef.com/users/harrydude98",
    year: "seventeen",
  },
];
export const india = [
  {
    name: "Shubham Atri",
    org: "IIT Bombay",
    img: "codechef.jpeg",
    linkedin: "https://www.linkedin.com/in/shubham-atri-2455a91a7/",
    github: "",
    codechef: "https://www.codechef.com/users/shubham__12",
    year: "nineteen",
  },
  {
    name: "Priyanshu Kumar",
    org: "IIIT Allahabad",
    img: "priyanshu.jpg",
    linkedin: "https://www.linkedin.com/in/priyanshukm/",
    github: "https://github.com/priyanshukm",
    codechef: "https://www.codechef.com/users/priyanshukm",
    year: "eighteen",
  },
  {
    name: "Yashit Garg",
    org: "IIIT Pune",
    img: "yashit.jpeg",
    linkedin: "https://www.linkedin.com/in/yashitgarg/",
    github: "https://github.com/yashitgarg/",
    codechef: "https://www.codechef.com/users/yashitgarg",
    year: "seventeen",
  },
];
export const world = [
  {
    name: "Kang",
    org: "Kim Chaek University of Technology",
    img: "codechef.jpeg",
    linkedin: "",
    github: "",
    codechef: "https://www.codechef.com/users/kut_hgs1997",
    year: "nineteen",
  },
  {
    name: "Himanshu Jaju",
    org: "Google",
    img: "himanshu.webp",
    linkedin: "https://www.linkedin.com/in/himanshujaju/",
    github: "https://github.com/himanshujaju",
    codechef: "https://www.codechef.com/users/himanshujaju",
    year: "eighteen",
  },
  {
    name: "Deep",
    org: "IIIT Pune",
    img: "codechef.jpeg",
    linkedin: "",
    github: "",
    codechef: "https://www.codechef.com/users/thedeep",
    year: "seventeen",
  },
];
