export const iiit = [
  {
    name: 'John DoesntCare',
    org: 'IIIT Pune',
    img: '2.jpeg',
    linkedin: 'xyz',
    github: 'darshancool25',
    codechef: '',
    year: 'nineteen',
  },
  {
    name: 'John DoesntCare',
    org: 'IIIT Pune',
    img: '3.jpeg',
    linkedin: 'xyz',
    github: 'darshancool25',
    codechef: '',
    year: 'eighteen',
  },
  {
    name: 'John DoesntCare',
    org: 'IIIT Pune',
    img: '3.jpeg',
    linkedin: 'xyz',
    github: 'darshancool25',
    codechef: '',
    year: 'eighteen',
  },
];
export const india = [
  {
    name: 'John DoesntCare',
    org: 'IIIT Pune',
    img: '2.jpeg',
    linkedin: 'xyz',
    github: 'darshancool25',
    codechef: '',
    year: 'nineteen',
  },
  {
    name: 'John DoesntCare',
    org: 'IIIT Pune',
    img: '3.jpeg',
    linkedin: 'xyz',
    github: 'darshancool25',
    codechef: '',
    year: 'eighteen',
  },
  {
    name: 'John DoesntCare',
    org: 'IIIT Pune',
    img: '3.jpeg',
    linkedin: 'xyz',
    github: 'darshancool25',
    codechef: '',
    year: 'eighteen',
  },
];
export const world = [
  {
    name: 'John DoesntCare',
    org: 'IIIT Pune',
    img: '2.jpeg',
    linkedin: 'xyz',
    github: 'darshancool25',
    codechef: '',
    year: 'nineteen',
  },
  {
    name: 'John DoesntCare',
    org: 'IIIT Pune',
    img: '3.jpeg',
    linkedin: 'xyz',
    github: 'darshancool25',
    codechef: '',
    year: 'eighteen',
  },
  {
    name: 'John DoesntCare',
    org: 'IIIT Pune',
    img: '3.jpeg',
    linkedin: 'xyz',
    github: 'darshancool25',
    codechef: '',
    year: 'seventeen',
  },
];
