export const iiit = [
  {
    name: 'Harsh Prakash',
    org: 'IIIT Pune',
    img: 'harsh.jpg',
    linkedin: 'https://www.linkedin.com/in/harsh132/',
    github: 'https://github.com/harsh132',
    codechef: 'https://www.codechef.com/users/harsh132',
    year: 'nineteen',
  },
  {
    name: 'Darshan Lokhande',
    org: 'IIIT Pune',
    img: '3.jpeg',
    linkedin: 'https://www.linkedin.com/in/darshanlokhande/',
    github: 'https://github.com/darshancool25',
    codechef: 'https://www.codechef.com/users/darshancool25',
    year: 'eighteen',
  },
  {
    name: 'John Doe',
    org: 'IIIT Pune',
    img: 'codechef.jpeg',
    linkedin: '',
    github: '',
    codechef: '',
    year: 'seventeen',
  },
];
export const india = [
  {
    name: 'Shubham Atri',
    org: 'IIT Bombay',
    img: 'codechef.jpeg',
    linkedin: 'https://www.linkedin.com/',
    github: '',
    codechef: 'https://www.codechef.com/users/shubham__12',
    year: 'nineteen',
  },
  {
    name: 'Priyanshu Kumar',
    org: 'IIIT Allahabad',
    img: 'priyanshu.jpg',
    linkedin: 'https://www.linkedin.com/in/priyanshukm/',
    github: 'https://github.com/priyanshukm',
    codechef: 'https://www.codechef.com/users/priyanshukm',
    year: 'eighteen',
  },
  {
    name: 'John Doe',
    org: 'IIIT Pune',
    img: 'codechef.jpeg',
    linkedin: '',
    github: '',
    codechef: '',
    year: 'seventeen',
  },
];
export const world = [
  {
    name: 'Kang',
    org: 'Kim Chaek University of Technology',
    img: 'codechef.jpeg',
    linkedin: '',
    github: '',
    codechef: 'https://www.codechef.com/users/kut_hgs1997',
    year: 'nineteen',
  },
  {
    name: 'Himanshu Jaju',
    org: 'Google',
    img: 'himanshu.webp',
    linkedin: 'https://www.linkedin.com/in/himanshujaju/',
    github: 'https://github.com/himanshujaju',
    codechef: 'https://www.codechef.com/users/himanshujaju',
    year: 'eighteen',
  },
  {
    name: 'John Doe',
    org: 'IIIT Pune',
    img: 'codechef.jpeg',
    linkedin: '',
    github: '',
    codechef: '',
    year: 'seventeen',
  },
];
